version: "3.9"
services:
  ganache:
    build:
      context: ./ganache
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
    volumes:
      - ./ganache-data:/data # Para persistir datos opcionalmente
    command: --host 0.0.0.0 --accounts 10 --defaultBalanceEther 1000
