version: '3.9'
services:
  db:
    image: postgres:15
    container_name: ids_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ids

  api:
    build:
      context: ./api
    container_name: ids_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/ids

  processor:
    build:
      context: ./processor
    container_name: ids_processor
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/ids

volumes:
  db_data: